<?php

namespace App\Exceptions;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        $middleware = $request->route()->middleware();
        if(in_array('api', $middleware)){
            return response()->json([
                'error' => true,
                'msg' => $e->getMessage(),
            ], $e->getCode());
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

    protected function unauthenticated($request, AuthenticationException $exception)
    {
        $middleware = $request->route()->middleware();
        if(in_array('api', $middleware)){
            return response()->json([
                'error' => true,
                'msg' => 'Unauthenticated',
            ], 401);
        }
        return parent::unauthenticated($request, $exception);

    }
}
